---
title: "smxapp"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{smxapp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Install stuff:

```{r, eval = FALSE}
devtools::install_github("einarhjorleifsson/smxapp",
                         dependencies = FALSE,
                         build_vignettes = TRUE)
devtools::install_github("fishvice/xe", 
                         dependencies = FALSE, 
                         build_vignettes = TRUE)
```

Some minimum information on the xe-package you can get via:
```{r, eval = FALSE}
browseVignettes(package = "xe")
```

And for the smxapp-package via:
```{r, eval = FALSE}
browseVignettes(package = "smxapp")
```

You can obtain some minimum files to load into Hafvog at ftp://ftp.hafro.is/pub/reiknid/einar/hafvog

For the smx app you could do:
```{r, eval = FALSE}
library(tidyverse)
library(lubridate)
library(sp)
library(ROracle)
library(xe)
con <- connect_xe()
res <- import_smx(con)
export_for_smxapp(con, res, cruise = c("A4-2018", "TL1-2018", "TH1-2018", "B3-2018"))
```

Once done go:

* File -> New file -> Rmarkdown... -> From Template --> smx dashboard
* Press Run Document
